name: end_to_end_test
version: 0.0.3
publish_to: none
description: >
  Tests, not for publishing.
homepage: https://github.com/victorevox/flutils

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_collection: "5.0.0"
  built_value: ^8.0.0
  flutils:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  build: ^1.0.0
  build_runner: ^1.0.0
  built_value_generator: ^8.0.0
